"""Arabic and mixed Arabic/English paraphrases for the intent head.

These are training and held-out texts, not runtime rules. The held-out
Vodafone renewal and the held-out CIB account-debit wording must stay out
of the training list. Nearby paraphrases teach the same meaning.
"""

DEVICE_RENEWAL = "عفواً، رصيدك غير كافٍ لتجديد باقة Plus 6000. برجاء شحن 65 جنيه"

EXTRA_TRAIN = {
    "card_purchase": [
        "اكتمل شراء البطاقة من المتجر وخرج المبلغ",
        "استخدمت البطاقة في المكتبة وتمت العملية",
        "المتجر حصل المبلغ من البطاقة بنجاح",
        "المتجر حصل القيمة عبر البطاقة المرتبطة",
        "حُصّل المبلغ من خلال بطاقتك لدى المكتبة",
        "عملية البيع بالبطاقة في الصيدلية اكتملت",
        "Your card sale اكتملت في المقهى وخرج المبلغ",
        "تم دفع ثمن المشتريات بالبطاقة لدى المطعم",
        "Your account ending with ****6620 is debited with amount EGP 44.00DR on 03 FEB 2025 for a purchase at the pharmacy.",
        "The account was debited for a completed purchase at the grocery. Available balance is now EGP 700.00.",
        "A card purchase at the cafe debited the account. Available limit afterwards is 9500.",
        "Your account was debited because the bookstore purchase completed. The remaining balance is quoted after the sale.",
        "تم خصم ثمن الشراء من الحساب بعد اكتمال عملية البطاقة في المتجر. الرصيد المتاح مذكور بعد العملية.",
        "The shop purchase finished and the account was debited. Available balance remains listed underneath.",
        "Your credit card ****6620 was charged EGP 44.00 at the bookstore on 03/02/2025 at 18:11.",
        "EGP 18.00 was spent using card ****1008 at the pharmacy.",
    ],
    "failed_card_purchase": [
        "رفض البنك محاولة الشراء بالبطاقة ولم يخرج شيء",
        "لم يكتمل الدفع في المتجر والبطاقة لم تُخصم",
        "المحاولة عند جهاز الدفع فشلت قبل تحصيل أي مبلغ",
        "المتجر لم يحصل على قيمة السلة لأن العملية رُفضت",
        "Card checkout declined ولم يتم تحصيل المبلغ من البطاقة",
        "تعذر إتمام الشراء بالبطاقة وبقي الحساب كما هو",
    ],
    "transfer_out": [
        "أُرسل المبلغ من المحفظة إلى نورا ووصلها",
        "تحويل صادر إلى كريم اكتمل",
        "خرجت القيمة من محفظتك إلى المستفيد",
        "تم إرسال الأموال إلى هناء بنجاح",
        "Wallet send to Omar اكتمل ووصل المبلغ",
        "The peer send left your side and reached the other person.",
        "دفعة بين الأفراد خرجت من رصيدك ووصلت للطرف الآخر",
        "حولت مبلغاً من المحفظة إلى أخيك",
        "The peer payment left your balance and reached Omar.",
        "A peer payment left the balance you hold and reached Layla.",
        "Your peer payment left your side of the balance and reached Karim.",
        "The peer send left your balance and the other person received it.",
        "Money left your balance when the peer payment reached the roommate.",
        "أرسلت 150 جنيهاً من محفظتك إلى ليلى وخرج المبلغ",
        "أرسلت مبلغاً من محفظتك إلى عمر فانخفض رصيدك",
        "من محفظتك أُرسلت القيمة إلى المستفيد",
        "أُرسلت الأموال من محفظتك نحو المستلم وقلّ ما تبقى لديك",
        "You sent جنيه from your wallet إلى سارة and your side decreased",
        "التحويل خرج من محفظتك إلى المستلم بعد أن أرسلته",
        "Your account ending with ****4412 is debited with amount EGP 250.00DR on 12 JAN 2025 with transfer to another account.",
        "The account was debited once the outward transfer to the other account had completed.",
        "A completed transfer moved funds out, and the source account was debited for that amount.",
        "Money left this account because a transfer to another account finished.",
        "We debited the account after the transfer reached the other account.",
        "حسابك خُصم منه المبلغ لأن التحويل إلى حساب آخر اكتمل.",
        "تم خصم القيمة من الحساب بعد أن وصل التحويل إلى الحساب الآخر.",
        "التحويل الصادر اكتمل فنُقص الحساب بالمبلغ الذي غادر.",
        "Your account was debited USD 40.00 for a completed transfer to another account. Available balance is USD 800.00.",
        "Account 7781 was debited after the transfer to the other account posted. Remaining balance EGP 640.00.",
        "A completed inter-account transfer debited the source account. The available balance afterwards is 2200 pounds.",
        "The outward transfer posted and the account balance fell because the funds had left.",
        "Your account ending in 9021 was debited for a transfer that another account received.",
        "Debit posted on the account: the transfer to the destination account is complete. Available limit is still shown below.",
    ],
    "transfer_in": [
        "وصلك تحويل من نورا إلى المحفظة",
        "أموال واردة من كريم وصلت إلى جانبك",
        "استقبلت محفظتك مبلغاً من هناء",
        "Incoming transfer from Layla وصل إلى حسابك",
        "مبلغ أرسله قريبك وصل إلى محفظتك",
        "استلمت الآن أموالاً جاءتك من أحد الأقارب",
        "وصل تحويل من قريب لك إلى الحساب وهو إيصال استلام",
        "ابن العم أرسل مبلغاً وقد استلمته المحفظة",
        "أموال أحد الأقارب وصلت إلى جانبك الآن",
        "A sum sent by a relative has landed in your wallet.",
        "Your account ending with ****3304 is credited with amount EGP 200.00CR on 02 FEB 2025 from a transfer by another account.",
        "A transfer from another account credited this account. Available balance is now EGP 1,500.00.",
        "The account was credited because an incoming transfer from another account completed.",
        "Funds arrived from another account, so this account was credited.",
        "تم إضافة المبلغ إلى الحساب لأن تحويلاً وارداً من حساب آخر اكتمل.",
        "حسابك أُضيف إليه مبلغ بعد اكتمال تحويل من حساب آخر. الرصيد المتاح مذكور للعلم.",
        "Incoming transfer posted. Your account was credited and the available balance increased.",
    ],
    "failed_transfer": [
        "تعذر إرسال المبلغ إلى عمر ولم تتحرك القيمة",
        "تحويل المحفظة إلى ليلى رُفض ولم يصلها شيء",
        "لم يغادر المبلغ لأن الإرسال لم يكتمل",
        "المستفيد لم يستلم شيئاً لأن التحويل فشل",
        "تعذر نقل المبلغ إلى الطرف الآخر ولم يخرج شيء",
        "لم نتمكن من نقل أموال المحفظة وبقيت القيمة مكانها",
        "Unable to move the wallet funds. Nothing reached the recipient.",
        "Transfer to Sam failed ولم يخرج أي مبلغ",
    ],
    "cash_withdrawal": [
        "صُرفت النقود من الماكينة",
        "سحبت أوراقاً نقدية من الصراف",
        "الماكينة أخرجت الكاش المطلوب",
        "خرجت نقود ورقية من الماكينة إلى يدك",
        "أوراق نقدية خرجت من جهاز الصرف",
        "Cash came out من الصراف الآلي",
    ],
    "refund": [
        "أعاد البائع ثمن السلعة بعد قبول الإرجاع",
        "رجع المبلغ من المتجر بسبب المرتجع",
        "عاد المال من التاجر لأن المنتج أُرجع",
        "المبلغ رجع إليك من البائع بعد المرتجع",
        "المتجر أصدر ائتماناً مقابل المنتج المرجع",
        "The shop returned 75 جنيه بعد قبول المرتجع",
        "عاد المبلغ من التاجر بعد أن قُبل المرتجع",
        "التاجر أعاد ثمن السلعة لأن الإرجاع اكتمل",
        "Money came back from the merchant after the return was accepted.",
    ],
    "reversal": [
        "أُلغي القيد السابق وعاد المبلغ",
        "العملية السابقة أُبطلت واستعيدت القيمة",
        "البنك تراجع عن الخصم السابق",
        "أُبطلت الحركة السابقة وعادت الأموال إلى الحساب",
        "The earlier debit was undone by the issuer and restored.",
        "The earlier posting was voided وعاد المبلغ",
        "An earlier debit was cancelled بواسطة البنك وعاد المبلغ",
        "The bank undid a previous debit بواسطة الجهة المصدرة",
        "خصم سابق تم التراجع عنه by the bank and the sum returned",
        "An earlier charge was voided بواسطة المؤسسة المالية",
        "البنك ألغى قيداً سابقاً وأعاد القيمة إلى الحساب",
    ],
    "fee": [
        "أضاف البنك رسماً إدارياً على الحساب",
        "احتُسبت مصاريف خدمة من المؤسسة",
        "نزل رسم شهري على الحساب",
        "A bank fee of 5 جنيه تم قيده على الحساب",
        "مُحصّل رسم صيانة من الحساب وليس ثمن شراء",
        "تكلفة الصيانة حُصّلت كرسم من مزود الحساب",
        "رسوم صيانة قُيدت على الحساب كمصروف مؤسسي",
        "احتُسبت تكلفة الصيانة كرسم وليست عملية شراء بالبطاقة",
        "مُحصّل مصروف صيانة صغير مقابل خدمة الحساب",
        "A maintenance levy was collected by the institution, not a shop.",
    ],
    "payment": [
        "سُددت فاتورة الكهرباء بالكامل",
        "دفعت الإيجار للمالك وأُغلقت الفاتورة",
        "اكتمل سداد فاتورة العيادة",
        "The water bill تم سداده بالكامل",
    ],
    "payment_due": [
        "تذكير بأن الفاتورة ما زالت مفتوحة ولم تُسدد",
        "موعد الاستحقاق اقترب والمبلغ لم يخرج بعد",
        "هذا إشعار بمبلغ مستحق وليس إيصالاً",
        "Payment is still due ولم يتم السداد",
    ],
    "statement": [
        "كشف الحساب عن الفترة جاهز للاطلاع",
        "ملخص الدورة متاح وهذا ليس خصماً جديداً",
        "أُعد كشف الحساب دون أي خصم جديد",
        "وثيقة الفترة جاهزة وهي ليست إشعار رصيد فقط",
        "Your statement جاهز ولا يحتوي حركة جديدة",
    ],
    "renewal_attempt": [
        "تعذر استمرار الخطة لأن المبلغ المتاح لا يغطي المطلوب",
        "لم يكتمل تمديد الاشتراك فالمتبقي أقل من سعر الاستمرار",
        "توقفت محاولة إبقاء الخدمة قبل أن يُخصم شيء",
        "الاشتراك لم يتجدد. زِد الرصيد ثم أعد المحاولة",
        "Renewal stopped لأن المتاح أقل من سعر الباقة",
        "لا يوجد مبلغ كافٍ to keep the monthly bundle active",
        "نأسف، استمرار الباقة لم يتم لنقص القيمة المطلوبة",
        "عفواً الرصيد غير كافٍ لتجديد الباقة. برجاء الشحن",
        "باقة الإنترنت لم تتجدد لأن الرصيد غير كافٍ",
        "برجاء شحن الخط لأن تجديد الباقة لم يكتمل",
        "المبلغ المطلوب غير متوفر لاستكمال تجديد الباقة",
        "عفواً، لا يوجد رصيد كافٍ لاستكمال تجديد الباقة",
        "استمرار الخدمة توقف قبل الاكتمال بسبب نقص الرصيد",
        "تجديد الباقة لم يتم. اشحن ثم أعد المحاولة",
        "الخدمة لم تُمدد. أضف رصيداً قبل إعادة المحاولة",
        "استمرار الباقة توقف لأن الرصيد لا يكفي والخدمة لم تعد",
        "توقفت الباقة عن الاستمرار. اشحن الخط كي تعود الخدمة لاحقاً",
        "لم يعد هناك استمرار للباقة. الخدمة متوقفة حتى يتم الشحن",
        "الباقة توقفت ولم تبدأ دورة جديدة. أعد الشحن قبل عودة الخدمة",
        "توقف استمرار الاشتراك والخدمة غير متاحة إلى أن تشحن",
        "The bundle stay stopped. Recharge the line before service comes back.",
    ],
    "renewal_success": [
        "تم تمديد الاشتراك والخدمة ما زالت تعمل",
        "استمرار الباقة اكتمل والدورة الجديدة فعالة",
        "الاشتراك تجدد والوصول ما زال متاحاً",
        "The monthly bundle continued بنجاح والخدمة تعمل",
        "دُفعت قيمة استمرار الخطة ولم تنقطع الخدمة",
        "الباقة بقيت مفعلة لدورة أخرى",
        "تم تجديد الاشتراك بنجاح والخدمة مستمرة",
        "تجديد الباقة اكتمل دون انقطاع",
        "Your bundle renewal finished successfully",
    ],
    "service_recharge": [
        "تم شحن رصيد الخط بنجاح وزاد الرصيد",
        "إعادة تعبئة كارت الخط اكتملت",
        "Airtime refill اكتمل على الخط",
        "الخط المدفوع مسبقاً حصل على رصيد مكالمات إضافي",
        "رصيد المكالمات على الخط المدفوع مسبقاً زاد بعد التعبئة",
        "استلم خطك المدفوع مقدماً دقائق مكالمات إضافية",
        "تعبئة الخط المدفوع مسبقاً أضافت رصيد مكالمات",
        "The prepaid line received airtime رصيد مكالمات",
        "شحن كارت الخط زاد وقت المكالمات وليس تحويلاً لمحفظة",
    ],
    "balance": [
        "رصيدك الحالي إشعار فقط دون أي حركة",
        "المتاح في الحساب الآن دون خصم أو إضافة عملية",
        "هذا بيان بالمبلغ الموجود وليس معاملة",
        "Available balance الآن دون أي حركة جديدة",
        "رصيد الخط الحالي للعلم فقط",
        "لقطة للمبلغ الجالس في الحساب دون رسوم",
        "ثمانون جنيهاً هي المتاح الآن وهذا إشعار",
        "No activity, المتاح للعلم فقط وليس عرضاً",
        "Your account ending with ****5521 has available balance EGP 300.00. Nothing was debited and no transfer occurred.",
        "Account balance for the account ending 8830 is EGP 90.00. This is only a balance notice.",
        "Balance enquiry for account ****1904. No debit occurred and no transfer was sent.",
        "الرصيد المتاح للحساب إشعار فقط. لم يحدث خصم ولم يُرسل تحويل.",
        "Available balance on the account is unchanged. This note does not debit the account.",
        "The account ending 2290 still holds the same sum. Nothing was transferred and nothing was spent.",
        "Your account ending with ****7712 has available balance EGP 80.00. No transfer or debit took place.",
        "Available balance for the account ending ****4188 is EGP 60. Nothing left the account. No transfer was made.",
        "This is only the balance of the account ending 6155. A transfer did not happen and the account was not debited.",
        "Balance snapshot for account ****2844: EGP 15.50. The account was not debited and no money was transferred.",
        "Your account ending with ****9090 shows EGP 42.00 available. There was no debit and there was no transfer.",
        "رصيد الحساب المنتهي بـ 7712 إشعار فقط. لم يُخصم شيء ولم يخرج تحويل.",
    ],
    "promotion": [
        "عرض خاص لهذا الأسبوع وليس إيصالاً",
        "استخدم كود الحملة في الزيارة القادمة",
        "رسالة تسويقية بدون أي تحصيل",
        "Special offer هذا الأسبوع، ليست عملية على الحساب",
        "Marketing note: ميزة للمشتركين إذا رغبوا بالمشاركة",
        "رسالة دعائية عن ميزة موسمية بلا أي قيد",
        "Marketing note: عرض موسمي يمكنك اختيار المشاركة فيه",
        "Marketing note: ميزة الموسم متاحة إذا رغبت بالانضمام",
        "ملاحظة تسويق: ميزة موسم جديد والمشاركة اختيارية وليست عملية",
        "A marketing note about a seasonal perk if you decide to join.",
        "رسالة تسويقية عن ميزة موسمية والمشاركة قرارك أنت",
    ],
    "otp": [
        "رمز الدخول لمرة واحدة لا تشاركه مع أحد",
        "كود التحقق خاص بالجلسة فقط",
        "Your OTP لتأكيد الهوية وليس عملية مكتملة",
        "لا ترسل رمز الأمان هذا لأي شخص",
        "لا تشارك رمز الدخول 778899 مع أي شخص",
        "محقق الدخول رقم سري فلا ترسله إلى أحد",
        "لا تعطي رمز محقق الجلسة 102938 لأي طرف",
        "Do not share محقق الدخول with anyone. The code is 445566",
        "رمز محقق الدخول هذا للجلسة فقط وليس رسالة عادية",
    ],
    "ambiguous_movement": [
        "غير واضح هل رُد المبلغ أم أُلغي القيد",
        "قد يكون مرتجعاً أو إلغاءً للعملية السابقة",
        "Refund or reversal غير محدد في هذه الرسالة",
    ],
    "other": [
        "هنتقابل بكرة",
        "المفتاح الاحتياطي في الدرج",
        "صباح الخير",
        "Hello نراك غداً",
        "كيف حالك اليوم",
        "المفتاح تحت الحصيرة عند الباب",
        "الدفتر على المكتب",
        "نتقابل عند المدخل",
        "Your hospital appointment is booked for 12/08/2026 at 09:00. Call 0233344455 to change it. Patient file 55210.",
        "Clinic visit reminder for tomorrow morning. Bring your papers. Reference 7712 is only a file number.",
        "تم حجز موعد في العيادة الساعة التاسعة. للاتصال 0222222222",
        "نتائج التحاليل جاهزة في الاستقبال. رقم الملف 44190 وهذا ليس تحويلاً.",
        "Your restaurant order is prepared. Pickup number 6601.",
        "The kitchen finished the meal. Order number 2291 is ready at the counter.",
        "طلب المطعم صار جاهزاً. رقم الاستلام 3381.",
        "Thanks for eating with us tonight. The table total was EGP 180. Come back soon.",
        "We enjoyed hosting you. The bill at the table was 95 pounds.",
        "شكرا لزيارتكم المطعم. قيمة الفاتورة على الطاولة 150 جنيهاً ونتمنى عودتكم.",
    ],
}

EXTRA_HELD = {
    "card_purchase": [
        "تم استخدام بطاقتك لشراء مبلغ 65 جنيه لدى المتجر",
        "اكتملت حركة البطاقة في المكتبة مقابل 18 جنيهاً",
        "المتجر حصل 90 درهماً عبر بطاقتك المرتبطة",
        "The retailer collected the amount through بطاقتك بنجاح",
        "Your account ending with ****2219 is debited with amount EGP 54.00DR on 04 APR 2024 for a purchase at the market.",
        "The account was debited for a purchase at the grocery. Available balance is shown afterwards.",
    ],
    "failed_card_purchase": [
        "حاول المتجر أخذ المبلغ من البطاقة لكن المحاولة رُفضت",
        "تفويض البطاقة فشل قبل أن يغادر أي مبلغ الحساب",
        "لم يُسجل خصم. الدفع عند الكشك لم يكتمل",
        "Merchant request rejected ولم يُحصل شيء من البطاقة",
    ],
    "transfer_out": [
        "أرسلت 200 جنيه من محفظتك إلى نورا",
        "أموال المحفظة انتقلت بنجاح إلى صاحب الحساب كريم",
        "التحويل بين الأفراد خرج من رصيدك ووصل هناء",
        "A completed remittance ذهب إلى أخيك من المحفظة",
        "Your account ending with ******9438 is debited with amount EGP 31.89DR on 31 MAR 2024 with transfer to another account.",
        "The account was debited because a transfer to another account completed on 31 March.",
        "Funds left the account through a completed transfer. The debit has posted.",
        "A completed transfer to another account debited the account. Available balance afterwards is EGP 640.00.",
        "Your account was debited EGP 75.00 for a transfer to another account. Available limit remains EGP 4,000.00.",
        "خُصم من حسابك مبلغ لأن تحويلاً مكتملاً خرج إلى حساب آخر.",
    ],
    "failed_transfer": [
        "المحفظة لم تستطع إرسال المال إلى عمر لأن المحاولة لم تنته",
        "طلب التحويل إلى ليلى رُفض ولم تتحرك قيمة",
        "تعذر نقل أموال المحفظة إلى المستلم",
        "Outgoing remittance did not go through والمستلم لم يستلم شيئاً",
    ],
    "renewal_attempt": [
        DEVICE_RENEWAL,
        "فشل تجديد الباقة لعدم كفاية الرصيد. يرجى إعادة الشحن",
        "Plus 6000 لم يتم تجديدها لأن الرصيد غير كافٍ، اشحن 65 جنيه",
        "استمرار الباقة توقف. اشحن الخط قبل أن تعود الخدمة",
        "The bundle could not renew لأن الرصيد أقل من 65 جنيه",
    ],
    "renewal_success": [
        "تم تجديد باقتك بنجاح",
        "الباقة عادت للعمل بعد الاستمرار المجدول",
        "الخطة الشهرية استمرت بنجاح والخدمة متاحة",
        "Subscription extension finished والدورة الجديدة مفتوحة",
    ],
    "balance": [
        "رصيد المحفظة الحالي 40 جنيهاً وهذا للعلم",
        "المتاح الآن: 1250 جنيهاً دون حركة",
        "لقطة للمبلغ الموجود في الحساب: ثمانون جنيهاً",
        "No activity, المتاح 15.50 جنيه فقط كإشعار",
        "Your account ending with ****1008 has available balance EGP 500.00. No transfer or debit took place.",
        "Available balance is EGP 1,400.00. This notice does not debit the account and does not send a transfer.",
    ],
    "promotion": [
        "هذا الأسبوع فقط استمتع بعرض خاص عند الزيارة",
        "دعوة حصرية: حملة محدودة بانتظارك",
        "افتح الميزة بإدخال رمز الحملة",
        "Marketing note: ميزة موسمية إذا اخترت المشاركة",
    ],
    "otp": [
        "استخدم 482193 كرمز سري لمرة واحدة للموافقة على الجلسة",
        "أُصدر رمز مؤقت للدخول: 119900",
        "لا تشارك محقق الدخول 554433 مع أي شخص",
        "Security challenge للجلسة هو 908172",
    ],
    "refund": [
        "أعاد المتجر 75 جنيهاً بعد قبول المرتجع",
        "عاد المال من التاجر بعد الإرجاع",
        "أصدر المتجر ائتماناً مقابل الصنف المرجع",
        "You received the purchase amount back من البائع",
    ],
    "reversal": [
        "القيد السابق أُلغي وأُعيد المبلغ",
        "ألغينا القيد السابق واستعدنا القيمة",
        "أُبطلت العملية وعادت الأموال",
        "An earlier debit was undone بواسطة البنك",
    ],
    "fee": [
        "أُضيف رسم إداري 5 جنيهات إلى الحساب",
        "فرضت المؤسسة رسماً صغيراً مقابل الخدمة",
        "مُحصّل تكلفة صيانة خمسة جنيهات",
        "Banking charges بقيمة 5 جنيهات قُيدت",
    ],
    "transfer_in": [
        "مبلغ من ابن عمك وصل الآن",
        "Incoming value from Nora وصل إلى جانبك",
        "Your account was credited with amount EGP 120.00CR on 02 APR 2024 from a transfer by another account.",
        "An incoming transfer from another account has credited your account. Available balance is EGP 2,040.00.",
    ],
    "cash_withdrawal": [
        "خرجت أوراق نقدية من الماكينة إليك",
        "أخذت نقداً من جهاز الصرف",
    ],
    "payment": [
        "فاتورة العيادة أُغلقت بعد أن سددتها",
        "الإيجار وصل المالك والفاتورة انتهت",
    ],
    "payment_due": [
        "الفاتورة ما زالت مفتوحة والتسوية لاحقة",
        "تذكير وصل بأن المبلغ لم يُسدد بعد",
    ],
    "statement": [
        "ملخص الفترة جاهز للفتح",
        "أُنشئ كشف للحساب بلا خصم جديد",
    ],
    "service_recharge": [
        "زاد وقت المكالمات بعد تعبئة ناجحة للخط",
        "الخط المدفوع مسبقاً استلم رصيد مكالمات",
    ],
    "ambiguous_movement": [
        "لا نستطيع تحديد هل هذا مرتجع أم إلغاء قيد",
        "Either a return or a void تم تطبيقه",
    ],
    "other": [
        "المفتاح تحت السجادة في المدخل",
        "الغدا الساعة اتنين وهات معاك دفتر",
        "Your clinic appointment is confirmed for 29/09/2026 at 10:30. Please call 0223456789 if you need to reschedule. File 10442.",
        "تم تأكيد موعدك في العيادة يوم 29/09/2026 الساعة 10:30. للاستفسار اتصل على 01234567890",
        "طلبكم جاهز للاستلام. رقم الطلب 1842. نتمنى لكم زيارة سعيدة.",
        "Thank you for dining with us. Your table bill was EGP 240. We hope to see you again.",
        "Lab results are ready at reception. Reference 22910. This is not a payment request.",
        "Your order from the restaurant is ready. Order 7731.",
        "Reminder: hospital visit tomorrow at 11:00. Patient number 883421.",
    ],
}
